version: '3'

services:
  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_DB=development
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=johann_gambolputty
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "server"
    environment:
      - POSTGRES_PASSWORD=johann_gambolputty
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/webpack-dev-server
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3035:3035'
